// Code generated by protoc-gen-go.
// source: protocol/messages/Request.proto
// DO NOT EDIT!

/*
Package limitd is a generated protocol buffer package.

It is generated from these files:
	protocol/messages/Request.proto
	protocol/messages/Response.proto

It has these top-level messages:
	Request
*/
package limitd

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Request_Method int32

const (
	Request_TAKE Request_Method = 0
	Request_WAIT Request_Method = 1
	Request_PUT  Request_Method = 2
)

var Request_Method_name = map[int32]string{
	0: "TAKE",
	1: "WAIT",
	2: "PUT",
}
var Request_Method_value = map[string]int32{
	"TAKE": 0,
	"WAIT": 1,
	"PUT":  2,
}

func (x Request_Method) Enum() *Request_Method {
	p := new(Request_Method)
	*p = x
	return p
}
func (x Request_Method) String() string {
	return proto.EnumName(Request_Method_name, int32(x))
}
func (x *Request_Method) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Request_Method_value, data, "Request_Method")
	if err != nil {
		return err
	}
	*x = Request_Method(value)
	return nil
}

type Request struct {
	Id               *string         `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Type             *string         `protobuf:"bytes,2,req,name=type" json:"type,omitempty"`
	Key              *string         `protobuf:"bytes,3,req,name=key" json:"key,omitempty"`
	Method           *Request_Method `protobuf:"varint,4,req,name=method,enum=limitd.Request_Method" json:"method,omitempty"`
	Count            *int32          `protobuf:"varint,5,opt,name=count,def=1" json:"count,omitempty"`
	All              *bool           `protobuf:"varint,6,opt,name=all,def=0" json:"all,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}

const Default_Request_Count int32 = 1
const Default_Request_All bool = false

func (m *Request) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Request) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *Request) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *Request) GetMethod() Request_Method {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return Request_TAKE
}

func (m *Request) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return Default_Request_Count
}

func (m *Request) GetAll() bool {
	if m != nil && m.All != nil {
		return *m.All
	}
	return Default_Request_All
}

func init() {
	proto.RegisterEnum("limitd.Request_Method", Request_Method_name, Request_Method_value)
}
